
module.exports = [
    {name:"-"},
    {name:'Below 5ft'},
    {name:'5ft 1"'},
    {name:'5ft 2"'},
    {name:'5ft 3"'},
    {name:'5ft 4"'},
    {name:'5ft 5"'},
    {name:'5ft 6"'},
    {name:'5ft 7"'},
    {name:'5ft 8"'},
    {name:'5ft 9"'},
    {name:'5ft 10"'},
    {name:'5ft 11"'},
    {name:'6ft'},
    {name:'6ft 1"'},
    {name:'6ft 2"'},
    {name:'6ft 3"'},
    {name:'6ft 4"'},
    {name:'6ft 5"'},
    {name:'6ft 6"'},
    {name:'6ft 7"'},
    {name:'6ft 8"'},
    {name:'6ft 9"'},
    {name:'6ft 10"'},
    {name:'6ft 11"'},
    {name:'7ft or Above'},
]
